function params = rovParameters()
% ROVPARAMETERS  Return fixed struct of BlueROV2 parameters (codegen‐safe)

  % basic
  rho    = 1000;          % kg/m^3
  g      = 9.82;          % m/s^2
  volume = 0.0134;        % m^3

  % rigid‐body
  mass = 13.5;            % kg
  I    = diag([0.26,0.23,0.37]);  % kg·m^2

  % added mass
  Ma_lin = [6.36;7.12;18.68];
  Ma_rot = [0.189;0.135;0.222];

  % damping
  D_lin  = [30;30;30;2;2;2];
  D_quad = [40;40;40;5;5;5];

  % CG/CB offsets
  rG = [0;0;0];
  rB = [0;0;-0.01];

  % ocean current
  current = [0;0;0];

  % build one struct literal
  params = struct( ...
    'mass',      mass,    ...
    'I',         I,       ...
    'Ma_lin',    Ma_lin,  ...
    'Ma_rot',    Ma_rot,  ...
    'D_lin',     D_lin,   ...
    'D_quad',    D_quad,  ...
    'rho',       rho,     ...
    'g',         g,       ...
    'volume',    volume,  ...
    'rG',        rG,      ...
    'rB',        rB,      ...
    'current',   current  ...
  );
end
